version: "3.8"

services:
  kong:
    image: kong:latest
    volumes:
      - ./kong:/usr/local/kong/declarative
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - 80:8000
      - 443:8443
      - 8001:8001
      - 8444:8444
    deploy:
      placement:
        constraints: [node.role == manager]
    links:
      - dbdriver
      - authservice

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 3002:3000

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: idp_database
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 8080:8080
    links:
      - mysql

  dbdriver:
    container_name: dbdriver
    build:
      dockerfile: Dockerfile
      context: ./DatabaseDriver
    volumes:
      - ./DatabaseDriver/src:/app/src
    command:
      - npm
      - run
      - start:docker
    ports:
      - 3000:3000
    links:
      - mysql

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  authservice:
    container_name: authservice
    build:
      dockerfile: Dockerfile
      context: ./AuthService
    environment:
        FLASK_RUN_PORT: 3000
    ports:
      - 3001:3000
    links:
      - mongo

volumes:
  grafana-data:
  mysql-data:
  mongo-data:
